import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Text from "../Components/Text/Text";
import DatePicker from "../Components/DatePicker/DatePicker";
import List from "../Components/List/List";
import NumberSlider from "../Components/NumberSlider/NumberSlider";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Skillbridge Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Skillbridge Calculator!</h1>
        <Text>Hello</Text>
        <List>
          <NumberSlider
            name={"ETSLeave"}
            label={"ETS Leave Amount"}
            value={50}
            onChange={() => {}}
          />
          <DatePicker
            name={"DOS"}
            label={"Date of Separation"}
            value={""}
            onChange={() => {}}
          />
          <DatePicker
            name={"SBEndDate"}
            label={"Skillbridge End Date"}
            value={""}
            onChange={() => {}}
          />
        </List>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
